### ISSUE TITLE
Add SR to existing DAR Patch (BUG)

### ISSUE THREAD

**Issue by trevorskaggs** [trevorskaggs/shelterly#518]
Dispatch > Deploy > Map Icon > Click DAR to Group With > Assign

```Internal Server Error: /evac/api/evacassignment/28/
Traceback (most recent call last):
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/sheltuser/shelterly/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/home/sheltuser/shelterly/evac/views.py", line 186, in perform_update
    animals_dict[animal.id] = {'name':animal_dict.get('name'), 'species':animal_dict.get('species'), 'status':animal_dict.get('status'), 'color_notes':animal_dict.get('color_notes'), 'pcolor':animal_dict.get('pcolor'), 'scolor':animal_dict.get('scolor'), 'shelter':animal_dict.get('shelter'), 'room':animal_dict.get('room')}
UnboundLocalError: local variable 'animal_dict' referenced before assignment```

**Comment by AlexMountain** [comment]
Fixed here: https://github.com/trevorskaggs/shelterly/commit/f39d07e4cd975334c4a7fa4419ecac1cc84fa5df
